// frontend/src/app/features/profile/profile.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { Observable } from 'rxjs';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { AuthService } from '../../core/auth.service';
import { User } from '../../core/auth.model';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.scss'],
  imports: [CommonModule, RouterModule, MatCardModule, MatButtonModule],
})
export class ProfileComponent {
  user$: Observable<User | null>;

  constructor(
    private readonly authService: AuthService,
    private readonly router: Router
  ) {
    this.user$ = this.authService.currentUser$;
  }

  logout(): void {
    this.authService.logout();
    this.router.navigate(['/login']);
  }
}

<div class="page-shell">
  <mat-card class="auth-card">
    <mat-card-header>
      <mat-card-title>User Profile</mat-card-title>
      <mat-card-subtitle>Secure account details</mat-card-subtitle>
    </mat-card-header>

    <mat-card-content *ngIf="user$ | async as user; else noUser">
      <p><strong>Username:</strong> {{ user.username }}</p>
      <p><strong>Display name:</strong> {{ user.displayName }}</p>
      <p><strong>Role:</strong> Administrator</p>
    </mat-card-content>

    <ng-template #noUser>
      <mat-card-content>
        <p>Unable to load profile details.</p>
      </mat-card-content>
    </ng-template>

    <mat-card-actions>
      <button mat-stroked-button color="accent" (click)="logout()">Logout</button>
    </mat-card-actions>
  </mat-card>
</div>

// frontend/src/pages/Profile/Profile.jsx
import { useMemo } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import { getStoredUser, logout } from '../../utils/auth';

/**
 * Renders the protected profile view for the authenticated user.
 *
 * @returns {JSX.Element} The profile page view.
 */
export default function ProfilePage() {
  const navigate = useNavigate();
  const user = useMemo(() => getStoredUser(), []);

  if (!user) {
    return <Navigate to="/login" replace />;
  }

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  return (
    <div className="page-shell">
      <article className="auth-card profile-card">
        <header>
          <h1>User Profile</h1>
          <p>Secure account details</p>
        </header>

        <section className="profile-details">
          <p><strong>Username:</strong> {user.username}</p>
          <p><strong>Display name:</strong> {user.displayName}</p>
          <p><strong>Role:</strong> Administrator</p>
        </section>

        <footer>
          <button className="secondary-button" type="button" onClick={handleLogout}>Logout</button>
        </footer>
      </article>
    </div>
  );
}
