// frontend/src/app/features/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterModule, Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { AuthService } from '../../core/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  imports: [
    CommonModule,
    ReactiveFormsModule,
    RouterModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
  ],
})
export class LoginComponent {
  loginForm: FormGroup;
  loginError = false;

  constructor(
    private readonly fb: FormBuilder,
    private readonly authService: AuthService,
    private readonly router: Router
  ) {
    this.loginForm = this.fb.group({
      username: ['', [Validators.required]],
      password: ['', [Validators.required]],
    });
  }

  get username() {
    return this.loginForm.get('username');
  }

  get password() {
    return this.loginForm.get('password');
  }

  onSubmit(): void {
    this.loginError = false;

    if (this.loginForm.invalid) {
      this.loginForm.markAllAsTouched();
      return;
    }

    const username = this.username?.value as string;
    const password = this.password?.value as string;

    if (this.authService.login(username, password)) {
      this.router.navigate(['/profile']);
      return;
    }

    this.loginError = true;
  }
}

<div class="page-shell">
  <mat-card class="auth-card">
    <mat-card-header>
      <mat-card-title>Sign in</mat-card-title>
      <mat-card-subtitle>Enter your enterprise credentials</mat-card-subtitle>
    </mat-card-header>

    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
      <mat-card-content>
        <mat-form-field appearance="fill" class="full-width">
          <mat-label>Username</mat-label>
          <input matInput formControlName="username" autocomplete="username" />
          <mat-error *ngIf="username?.hasError('required') && username?.touched">
            Username is required.
          </mat-error>
        </mat-form-field>

        <mat-form-field appearance="fill" class="full-width">
          <mat-label>Password</mat-label>
          <input
            matInput
            type="password"
            formControlName="password"
            autocomplete="current-password"
          />
          <mat-error *ngIf="password?.hasError('required') && password?.touched">
            Password is required.
          </mat-error>
        </mat-form-field>

        <div *ngIf="loginError" class="error-message">
          Invalid username or password.
        </div>
      </mat-card-content>

      <mat-card-actions>
        <button mat-flat-button color="primary" type="submit" [disabled]="loginForm.invalid">
          Login
        </button>
      </mat-card-actions>
    </form>
  </mat-card>
</div>

// frontend/src/pages/Login/Login.jsx
import { useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { login } from '../../utils/auth';

/**
 * Renders the login screen for the ReqTrace React UI.
 *
 * @returns {JSX.Element} The login form view.
 */
export default function LoginPage() {
  const navigate = useNavigate();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [loginError, setLoginError] = useState(false);
  const [touched, setTouched] = useState({ username: false, password: false });

  const usernameInvalid = !username.trim() && touched.username;
  const passwordInvalid = !password && touched.password;

  const handleSubmit = (event) => {
    event.preventDefault();
    setTouched({ username: true, password: true });
    setLoginError(false);

    if (!username.trim() || !password) {
      return;
    }

    if (login(username, password)) {
      navigate('/profile');
      return;
    }

    setLoginError(true);
  };

  return (
    <div className="page-shell">
      <article className="auth-card">
        <header>
          <h1>Sign in</h1>
          <p>Enter your enterprise credentials</p>
        </header>

        <form onSubmit={handleSubmit} noValidate>
          <label className="field">
            <span>Username</span>
            <input
              type="text"
              aria-label="Username"
              value={username}
              onChange={(event) => setUsername(event.target.value)}
              onBlur={() => setTouched((prev) => ({ ...prev, username: true }))}
              autoComplete="username"
            />
            {usernameInvalid && <small>Username is required.</small>}
          </label>

          <label className="field">
            <span>Password</span>
            <input
              type="password"
              aria-label="Password"
              value={password}
              onChange={(event) => setPassword(event.target.value)}
              onBlur={() => setTouched((prev) => ({ ...prev, password: true }))}
              autoComplete="current-password"
            />
            {passwordInvalid && <small>Password is required.</small>}
          </label>

          {loginError && <div className="error-message">Invalid username or password.</div>}

          <button className="primary-button" type="submit">Login</button>
        </form>
      </article>
    </div>
  );
}
